### ISSUE TITLE
blank image folder

### ISSUE THREAD

**Issue by bramvera** [bavuongco10/qwerteeCrawler#1]
Hi, test it but does nothing, 
$ python 2.py 1 10000
Initialize a pool...
end job...

it just created an image folder but blank,
thanks

**Comment by bavuongco10** [comment]
Id from 1 to 10000 have no pictures, so you have to crawl from another
range like 80000 to 100000.

Vào 29-08-2016 2:31 CH, "brumie" notifications@github.com đã viết:

**Comment by bramvera** [comment]
thanks, working nicely
